export const countries = [
  { "iso_3166_1": "US", "english_name": "United States", "native_name": "United States" },
  { "iso_3166_1": "GB", "english_name": "United Kingdom", "native_name": "United Kingdom" },
  { "iso_3166_1": "CA", "english_name": "Canada", "native_name": "Canada" },
  { "iso_3166_1": "AU", "english_name": "Australia", "native_name": "Australia" },
  { "iso_3166_1": "FR", "english_name": "France", "native_name": "France" },
  { "iso_3166_1": "DE", "english_name": "Germany", "native_name": "Deutschland" },
  { "iso_3166_1": "IT", "english_name": "Italy", "native_name": "Italia" },
  { "iso_3166_1": "ES", "english_name": "Spain", "native_name": "España" },
  { "iso_3166_1": "JP", "english_name": "Japan", "native_name": "日本" },
  { "iso_3166_1": "CN", "english_name": "China", "native_name": "中国" },
  { "iso_3166_1": "IN", "english_name": "India", "native_name": "भारत" },
  { "iso_3166_1": "BR", "english_name": "Brazil", "native_name": "Brasil" },
  { "iso_3166_1": "RU", "english_name": "Russia", "native_name": "Россия" },
  { "iso_3166_1": "ZA", "english_name": "South Africa", "native_name": "South Africa" },
  { "iso_3166_1": "NG", "english_name": "Nigeria", "native_name": "Nigeria" },
  { "iso_3166_1": "EG", "english_name": "Egypt", "native_name": "مصر" },
  { "iso_3166_1": "KR", "english_name": "South Korea", "native_name": "대한민국" },
  { "iso_3166_1": "MX", "english_name": "Mexico", "native_name": "México" },
  { "iso_3166_1": "AR", "english_name": "Argentina", "native_name": "Argentina" },
  { "iso_3166_1": "CL", "english_name": "Chile", "native_name": "Chile" },
  { "iso_3166_1": "SA", "english_name": "Saudi Arabia", "native_name": "المملكة العربية السعودية" },
  { "iso_3166_1": "AE", "english_name": "United Arab Emirates", "native_name": "الإمارات العربية المتحدة" },
  { "iso_3166_1": "TR", "english_name": "Turkey", "native_name": "Türkiye" },
  { "iso_3166_1": "SE", "english_name": "Sweden", "native_name": "Sverige" },
  { "iso_3166_1": "NO", "english_name": "Norway", "native_name": "Norge" },
  { "iso_3166_1": "FI", "english_name": "Finland", "native_name": "Suomi" },
  { "iso_3166_1": "DK", "english_name": "Denmark", "native_name": "Danmark" },
  { "iso_3166_1": "NZ", "english_name": "New Zealand", "native_name": "New Zealand" },
  { "iso_3166_1": "PK", "english_name": "Pakistan", "native_name": "پاکستان" },
  { "iso_3166_1": "ID", "english_name": "Indonesia", "native_name": "Indonesia" },
  { "iso_3166_1": "TH", "english_name": "Thailand", "native_name": "ประเทศไทย" }
]